language: common lisp

install:
 - sudo apt-get install -y sbcl cl-quicklisp

script:
 - make test
 
# configure notifications (email, IRC, campfire etc)
# notifications:
#   irc: "irc.cat.pdx.edu#cs442"
